Default: &defaults
  user: MyBlog
  password: MyBlog
  host: localhost
  database: MyBlog
  connections: 10

Development:
  <<: *defaults

Testing:
  database: MyBlog_test
  <<: *defaults

Staging:
  database: MyBlog_staging
  connections: 100
  <<: *defaults

Production:
  database: MyBlog_production
  connections: 100
  host: localhost
  <<: *defaults
